services:
  # global nginx reverse proxy
  # receives HTTP from cloud VPS via WireGuard tunnel
  nginx:
    build: ./nginx
    container_name: global_nginx
    ports:
      - "10.66.66.3:80:80"

    # nginx must join every project's network to reach their containers
    networks:
      - courseselling-network
      - streamweaver-network

    restart: unless-stopped

# each project creates its own podman network
# declare them as external so nginx can join them
networks:
  courseselling-network:
    name: coursesellingapp-docker_courseselling
    external: true
  streamweaver-network:
    name: streamweaverv2_default
    external: true
