services:
  courseselling_app_frontend;
    build:
     context: #relative path to the repo 
     dockerfile: Dockerfile
    expose:
     - "80"
    networks:
     - app-network

  courseselling_backend:
   build: 
    context: #relative path to the repo 
    dockerfile: Dockerfile 
   expose:
    - "8080"
   networks: 
    - app-network

  