#Build stage 
FROM node:20-alpine AS builder

#Build using pnpm 
RUN corepack enable && corepack prepare pnpm@latest --activate 

WORKDIR /app

#Copy dependency files for better caching 
COPY package.json pnpm-lock.yaml ./

#Copy source code 
COPY . .

#Production stage 
FROM node:20-alpine 

#Install pnpm 
RUN corepack enable && corepack prepare pnpm@latest --activate

#ffmpeg 
RUN apk add --no-cache ffmpeg

WORKDIR /app

#Copy dependecy files and install production only deps 
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --prod --no-frozen-lockfile

#COPY source code 
COPY --from=builder /app/src ./src 

#create required directories for file uploads and processing
RUN mkdir -p ./public/temp ./public/chunkPlaylist

#Expose the backend port 
EXPOSE 8080

#start the server 
CMD ["node", "-r", "dotenv/config", "src/index.js", "--experimental-json_modules"]