server {
    listen 80;
    server_name seclan.live;

    client_max_body_size 500M;

    #for the ssl 
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    #for the backend 
    location /api/ {
        if ($request_method = 'OPTIONS') {
            add_header "Access-Control-Allow-Origin" "*" always;
            add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS";
            add_header "Access-Control-Allow-Headers" "Content-Type, Authorization" always;
            add_header "Access-Control-Max-Age" "86400" always;
            add_header "Content-Length" 0;
            return 204;
        }

        #add cors headers to all responses
        add_header "Access-Control-Allow-Origin" "*" always;
        add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS" always;
        add_header "Access-Control-Allow-Headers" "Content-Type, Authorization" always;
        
        proxy_pass https://streamweaver_backend:8080;

        #headers to allow main service to access details
        proxy_set_header Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #increase timeouts for long running videos
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        send_timeout 600s;

    }

    #for the frontend 
    location / {
        proxy_pass https://streamweaver_frontend:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}