server {
    listen 80;
    server_name seclan.live;
    
    location / {
        return 301 https://$host$request_uri;
    }
} 

server {
    listen 443 ssl;
    server_name seclan.live;

    #ssl certificates location 
    ssl_certificate /etc/letsencrypt/live/seclan.live/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/seclan.live/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;

    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    client_max_body_size 500M;

    #for the backend 
    location /api/ {
        if ($request_method = 'OPTIONS') {
            add_header "Access-Control-Allow-Origin" "*" always;
            add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS";
            add_header "Access-Control-Allow-Headers" "Content-Type, Authorization" always;
            add_header "Access-Control-Max-Age" "86400" always;
            add_header "Content-Length" 0;
            return 204;
        }

        #add cors headers to all responses
        add_header "Access-Control-Allow-Origin" "*" always;
        add_header "Access-Control-Allow-Methods" "GET, POST, OPTIONS" always;
        add_header "Access-Control-Allow-Headers" "Content-Type, Authorization" always;
        
        proxy_pass https://streamweaver_backend:9000;

        #headers to allow main service to access details
        proxy_set_header Host $host;
        proxy_set_header  X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        #increase timeouts for long running videos
        proxy_connect_timeout 600s;
        proxy_send_timeout 600s;
        proxy_read_timeout 600s;
        send_timeout 600s;

    }

    #for the frontend 
    location / {
        proxy_pass https://streamweaver_frontend:4000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}